### ISSUE TITLE
No such file or directory: 'auth/auth.yml'

### ISSUE THREAD

**Issue by shaft8472** [CyberPunkMetalHead/binance-trading-bot-new-coins#17]
`root@DietPi-Pi-119:~# python3 ~/new-coin-bot/main.py
Traceback (most recent call last):
  File "/root/new-coin-bot/main.py", line 1, in <module>
    from trade_client import *
  File "/root/new-coin-bot/trade_client.py", line 3, in <module>
    client = load_binance_creds('auth/auth.yml')
  File "/root/new-coin-bot/auth/binance_auth.py", line 8, in load_binance_creds
    with open(file) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'auth/auth.yml'`

So, there is actually a file there. If I execute: nano ~/new-coin-bot/auth/auth.yml I get the contents of that file.
What's happening here, why doesn't it see the auth file?

**Comment by pat-s** [comment]
It is a relative path, try starting the `main.py` file from the project root.

**Comment by MinaBasem** [comment]
> It is a relative path, try starting the `main.py` file from the project root.

When I run from the terminal it gives an error that there is no such file or directory, but if I run from VS Code it says permission denied, any solutions?

**Comment by shaft8472** [comment]
> 
> 
> It is a relative path, try starting the `main.py` file from the project root.

I'm sorry, I don't really understand. The project in itself is in a folder called "new-coin-bot". I'm running this on a raspberry pi so the whole directory is: root/new-coin-bot/main.py

auth.yml is located at root/new-coin-bot/auth/auth.yml

The structure is the same as the github structure.

**Comment by pat-s** [comment]
```
cd new-coin-bot/
python 3 main.py
```

**Comment by MinaBasem** [comment]
> ```
> cd new-coin-bot/
> python 3 main.py
> ```

No difference, it still doesn't detect the file

**Comment by easyguyme** [comment]
Hi @shaft8472 I think you need to rename the `auth.example.yml` to `auth.yml`

**Comment by shaft8472** [comment]
> 
> 
> Hi @shaft8472 I think you need to rename the `auth.example.yml` to `auth.yml`

It's not called aut.example.yml. As I've stated in OP when executing nano ~/new-coin-bot/auth/auth.yml it opens just fine.

**Comment by shaft8472** [comment]
> 
> 
> ```
> cd new-coin-bot/
> python3 main.py
> ```

Solution, thanks!
