### ISSUE TITLE
Eorror running the script

### ISSUE THREAD

**Issue by turvak** [CyberPunkMetalHead/binance-trading-bot-new-coins#21]
I'm having issues running the script at all. I get the FileNotFoundError: [Errno 2] No such file or directory: '/auth/auth.yml'

I'm executing via windows console just referencing the main.py:
C:\Users\usr1\Downloads\binance-trading-bot-new-coins-main\binance-trading-bot-new-coins-main/main.py

Also, I can't see what to enter on the line in auth.yml binance_tld: "BINANCE_TLD"

**Comment by pat-s** [comment]
dup of #17?

**Comment by imastoridis** [comment]
I personally ran it with "python main.py" and it works. I don't really know Python though, so it may not be the best way.

For the BINANCE_TLD you need to put "com" or "us" i guess if you are in the states.

**Comment by turvak** [comment]
Looks like putting in the TLD has made progress. This is the error I get now:

```
Traceback (most recent call last):
  File "C:\Users\usr1\trading-bot\main.py", line 219, in <module>
    main()
  File "C:\Users\usr1\trading-bot\main.py", line 66, in main
    tp = config['TRADE_OPTIONS']['TP']
TypeError: 'NoneType' object is not subscriptable
```

![image](https://user-images.githubusercontent.com/89772453/131420132-130a1369-1ee9-44ab-ac61-e965b290d8ba.png)


This is what is in the config.yml
`---
    TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 15
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 0.025
    # Test mode, set to false to use the live Binance account
    TEST: True
    #Stop loss in %
    SL: 3
    # Take profit in %
    TP: 5
    # Enable Trailing Stop Loss
    ENABLE_TSL: True
    # Trailing Stop in % from the current price
    TSL: 1
    # Trailing profit in % from the current price
    TTP: 1`

**Comment by turvak** [comment]
Okay strange - I downloaded the source again and its running. I must have made a syntax change somewhere. 

All working
