### ISSUE TITLE
Trailing stop loss on spot trade?

### ISSUE THREAD

**Issue by turvak** [CyberPunkMetalHead/binance-trading-bot-new-coins#30]
Forgive me if I'm wrong here. I'm seeing a few issues mentioning the sell order not executing. Could this be because you are setting a trailing stop-loss order on a spot trade?

Natively Binance only allows for TSL on futures. On spot trades, you can set limit or stop-loss orders but not of the trailing type.

Also just confirming that the json files are created when the script finds a new coin and executes. I don't see the json files but do see the references within the executed functions. 

Where did the frequency function go? Looks like we have no control of the API call frequency anymore. 

Thanks

**Comment by CyberPunkMetalHead** [comment]
The trailing stop loss is calculated locally, so instead of asking Binance to do it, we handle it locally and just send a sell request once the parameters match. The sell order issue is related to the format of the trades.json which needs fixing. Currently working fine in test mode.
