### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by bdisher** [CyberPunkMetalHead/binance-trading-bot-new-coins#36]
Hi, so I'm new to python, and i am getting ModuleNotFoundError for the  `from trade_client import *` . I have been googling for a couple hours and have not been able to fix it. Would appreciate any help. Thanks

![pycharm64_2021-09-04_21-46-44](https://user-images.githubusercontent.com/73045700/132112208-657bd1c6-ec59-4c60-98d1-deb15a15227b.png)

![pycharm64_2021-09-04_21-45-04](https://user-images.githubusercontent.com/73045700/132112182-af85b596-b330-464e-a147-822aed706c70.png)

**Comment by Emilvang** [comment]
Have you tried running it in a terminal, like Powershell? Just type "python main.py"

**Comment by Bela0** [comment]
Check out the blog post linked in the README.
You probably need to install the dependencies using pip:

`pip install python-binance` and
`pip install pyaml`

**Comment by bdisher** [comment]
> 
> 
> Have you tried running it in a terminal, like Powershell? Just type "python main.py" from the main directory of the project.

I have tried, it does not work. I have also tried everything in this video: https://www.youtube.com/watch?v=I9st-DgQoWc&ab_channel=PhilsBeginnerCode

![powershell_2021-09-05_15-46-07](https://user-images.githubusercontent.com/73045700/132139579-5bbf3ccf-18a0-48b5-8a5b-d590d6e03f30.png)

**Comment by bdisher** [comment]
> 
> 
> Check out the blog post linked in the README.
> You probably need to install the dependencies using pip:
> 
> `pip install python-binance` and
> `pip install pyaml`

I have read through the blog already, and followed all the steps. 

![pycharm64_2021-09-05_15-47-18](https://user-images.githubusercontent.com/73045700/132139610-e0d660d1-aef0-42b9-9fd6-18ef6d147e94.png)

**Comment by Emilvang** [comment]
You need to be in the folder. In explorer open the binance-trading-bot-new-coins folder and in where you see the path you type Powershell. Then you can type "python main.py" in there.

**Comment by Emilvang** [comment]
![githubhelp](https://user-images.githubusercontent.com/17877052/132139891-d3615489-0fb3-4c25-93e8-2a9d4dffc72c.png)

**Comment by stevenhgs** [comment]
It seems like you're using PyCharm, so you can just go to the tab File > Settings... > Project > Project Interpreter. 
There you can press on the "+" and search for the package you want to install.

**Comment by CadburySwaps** [comment]
![Screen Shot 2021-10-02 at 6 16 05 PM](https://user-images.githubusercontent.com/89444214/135716855-819e6e87-f8ea-445a-80d8-cbdf2f22b074.png)
hii can anyone help me ?
