### ISSUE TITLE
Feature Request - Order Max instead of Qty of Coins

### ISSUE THREAD

**Issue by Phando** [CyberPunkMetalHead/binance-trading-bot-new-coins#38]
Since you don't know the coin list price, it is hard to estimate how many coins to buy per the config. One thing I do know is what I am willing to wager. Why not add a flag to set an order maximum? That way I could say buy $100 regardless of the quantity being bought.

**Comment by Bela0** [comment]
I think the quantity describes the number of the pairing coins that are to be bought. By default it is 15 USDT, so equal to ~15 US$

**Comment by Phando** [comment]
Makes sense, thank you.
