### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by LakshithaKG** [CyberPunkMetalHead/binance-trading-bot-new-coins#4]
When running the program for a while, me and a friend of mine keeps getting `ConnectionResetError(54, 'Connection reset by peer')` error. Apparently, this is because the Client times out after a while.

**Comment by CyberPunkMetalHead** [comment]
How often does this happen? I'm unable to replicate this on my end.

**Comment by LakshithaKG** [comment]
Not too sure but after around 30 minutes to an hour. I'll have it run for a while and let you know in about 10 hours.

**Comment by LakshithaKG** [comment]
I was running it on the default config settings and my branch is even with the main so does this mean the issue is with my setup? Also, I'm not sure after how long the error occurred but it ran successfully for at least 2h.

<img width="1003" alt="Connection reset by peer error" src="https://user-images.githubusercontent.com/89327252/130513844-02974103-f818-4dfd-a233-f5759a7a30b0.png">
<img width="978" alt="Connection reset" src="https://user-images.githubusercontent.com/89327252/130515203-69579d08-40c7-40de-b5e8-29825df9c1ac.png">
