### ISSUE TITLE
Scrapper

### ISSUE THREAD

**Issue by Lautaro-L** [CyberPunkMetalHead/binance-trading-bot-new-coins#58]
I make a new coin bot that uses a scrapper to gather the new coins if you want to check out it I made a comment in the discussion thread, but i notice your filter on some keywords I think you're missing some like Cross, Perpetual

**Comment by CyberPunkMetalHead** [comment]
Why is this an issue?

**Comment by Lautaro-L** [comment]
I think it won't filter all the unwanted announcement like  Launchpool  unless you want it
