### ISSUE TITLE
Ran execpt block for lot_size. "TypeError: argument of type 'int' is not iterable"

### ISSUE THREAD

**Issue by Varingon** [CyberPunkMetalHead/binance-trading-bot-new-coins#6]
New coins detected: [{'symbol': 'TRIBEBTC', 'price': '0.00002194'}, {'symbol': 'TRIBEBNB', 'price': '0.00220000'}, {'symbol': 'TRIBEBUSD', 'price': '1.09470000'}, {'symbol': 'TRIBEUSDT', 'price': '1.07700000'}]
New coin detected, but TRIBEBTC is currently in portfolio, or pairing is not USDT
New coin detected, but TRIBEBNB is currently in portfolio, or pairing is not USDT
New coin detected, but TRIBEBUSD is currently in portfolio, or pairing is not USDT
Preparing to buy TRIBEUSDT
ran exept block for lot_size
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 153, in main
    volume = convert_volume(coin, qty, price)
  File "/binance/trade_client.py", line 29, in convert_volume
    if coin not in lot_size:
TypeError: argument of type 'int' is not iterable

**Comment by LakshithaKG** [comment]
Yeah, this issue is being caused by line 21 in trade_client.py. It should say something like `lot_size = {}` not `lot_size = 0`.

**Comment by CyberPunkMetalHead** [comment]
fixed :)
