### ISSUE TITLE
Important params unused

### ISSUE THREAD

**Issue by oularrea** [CyberPunkMetalHead/binance-trading-bot-new-coins#77]
Reviewing the code due to an error when executing the bog of "('Connection aborted.', ConnectionResetError (104, 'Connection reset by peer'))" and increasing the same error kept happening, I started to review the code and I see that the parameter `frequency = config ['TRADE_OPTIONS'] ['RUN_EVERY'] ` is not used in any part of the code, that's why this error happens. you could review it?

I have also checked that the parameter `coin_sl = order [coin] ['sl'] `is not used either, but I'm not sure how important it is to close trades at a loss.

**Comment by webdesign7** [comment]
I also noticed that, any ideas  @CyberPunkMetalHead  ?
