### ISSUE TITLE
connection aborted error

### ISSUE THREAD

**Issue by chestikoff** [CyberPunkMetalHead/binance-trading-bot-new-coins#8]
Testing your code on Mac OS. I've started getting this error since yesterday. It was fine before...
 
('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by Raynojam** [comment]
I have the same error, what was your fix?

**Comment by chestikoff** [comment]
I just tried a restart. So far it’s been fine, for roughly 16 hours now.

**Comment by Raynojam** [comment]
Thanks that sorted it
